platform :ios, '10.0'

target 'iThink' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# Pods for iThink
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'


  target 'iThinkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iThinkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
